try to avoid passsing absolute paths since windows is a douche
```
Error: /usr/bin/bash: D:a_tempa9e09e68-6166-48e4-8d72-a714baa92cb0QtInstallerFramework-windows-x86-4.1.1.exe: command not found
```